### ISSUE TITLE
[1.12.2] Major Bug with Living Armor.

### ISSUE THREAD

**Issue by SonicX8000** [Clownvin/Living-Enchantment#19] opened 2020-07-02 04:36 UTC
Minecraft: 1.12.2
Forge: 14.23.5.2854

Mods: 2
jei_1.12.2-4.15.0.291
living_enchantment-3.2.2

---

I am not sure what's going on but due to the update with changing the Damage Reductions for Living Armor, it's DR on the tool tip is rather... bugged. Here's some screenshots using the default config but with XP Share on.

![](https://cdn.discordapp.com/attachments/377171551155650560/728100878350811136/livingarmorbug01.PNG)
Enchanted some Diamond Armor with Living, slain an Iron Golem & got it to Level 3 and... uhh... what? 100% DR?

![](https://cdn.discordapp.com/attachments/377171551155650560/728100900408655923/livingarmorbug02.PNG)
Got some Gold Armor to Level 10, Now the DR is 40.7%. Huh?

![](https://cdn.discordapp.com/attachments/377171551155650560/728100963692445840/livingarmorbug03.PNG)
I removed a piece of gold armor and now I have 0% DR.

![](https://cdn.discordapp.com/attachments/377171551155650560/728100982684254318/livingarmorbug04.PNG)
With a little messing around, I managed to get the DR on non-Living Armor.

![](https://cdn.discordapp.com/attachments/377171551155650560/728101008000942200/livingarmorbug05.PNG)
Wearing a full set of Iron Armor at Level 2 and... 0% DR.

At first I thought it was only a visual glitch but apparently it isn't as you can get just one piece to a certian level, like 2, you'll have 100% DR thus making you immortal. Not even suffering the wrath of '/kill' will do anything.

---

If you're still adjusting the values for Living Armor DR, perhaps make it a static boost like if the config is at 2.0 effectiveness, each armor piece will grant 0.5% *2.0% for a set* per level. Like this...

Level 0 = 0.0% per piece. *0.0% for a set*
Level 1 = 0.5% per piece. *2.0% for a set*
Level 10 = 5.0% per piece. *20% for a set*
Level 20 = 10.0% per piece. *40% for a set*
Level 30 = 15.0% per piece. *60% for a set*
Level 40 = 20.0% per piece. *80.0% for a set*
Level 50 = 25.0% per piece. *100.0% for a set*
Level 100 = 50.0% per piece. *100.0% for a set due to cap.*

The hard cap would be 100%, and of course for users that don't want to have such armor go to 100% DR, they can cap the level where if capped at level 30 with the effectiveness that I listed... which is 2.0... the armor will only reach 60% of 100% DR.

This makes it a smooth level up where you get a steady boost to DR but as your level increases... so does the XP requirement. Not to mention it wouldn't be quite as powerful for the early levels giving such a big boost & it's more config friendly so users can get the DR value to where they want it.

P.S.
Not sure if 2.0 effectiveness is the right value as that may be 200.0%, so maybe it's 0.02 for it to be 2%, and 0.2 would be 20%, etc. You get the idea.

**Comment by Clownvin** [comment] 2020-07-02 05:15
The problem is that Math.log goes in the complete opposite direction of what I'd intended at levels under 7. At level 14, which is supposed to be the "diamond gear max enchant level" effectiveness, I'm going for about 10% a piece. In this fix, at least. Current log results are probably a little too high tbh.

**Comment by Clownvin** [comment] 2020-07-02 05:17
I should have a fix for it soon enough, just gotta try and get these numbers right.

**Comment by Clownvin** [comment] 2020-07-02 05:20
It's gotta be somewhat slow to increase, since its reduction for ALL types of damage.

**Comment by Clownvin** [comment] 2020-07-02 05:32
Okay, it should be fixed

**Closed as completed by Clownvin** 2020-07-02 05:32 UTC

**Comment by Z-Tunic** [comment] 2020-07-03 00:30
Early Levels still can give a big boost to DR.

In order for me to get the DR to 60.0% for a Lvl 30 Set... I had to set the effectiveness to 0.896. These are the DRs that the armor gives me.

4x Pieces = 60.0%
3x Pieces = 57.6%
2x Pieces = 53.8%
1x Piece = 45.9%

---

Now... for Level 1 Armor...

4x Pieces = 15.6%
3x Pieces = 11.5%
2x Pieces = 6.5%
1x Pieces = 0.0%

---

Now... for Level 2 Armor...

4x Pieces = 26.4%
3x Pieces = 21.5%
2x Pieces = 15.6%
1x Pieces = 6.5%

---

You sure that the scaling suggestion that I mentioned can't be an option? Because it's actually tricky trying to balance around this as early levels give big boosts but if I lower it then the level cap will have to be raised higher.
